### ISSUE TITLE
How can I run this now

### ISSUE THREAD

**Issue by GordenSun** [pawansharmaaaa/Lip_Wise_GFPGAN#1]
Hi, I love this version so much, but it can't work now, because the repo is not available. How can I run it ?

!git clone https://github.com/pawansharmaaaa/Wav2Lip_Mod.git

**Comment by pawansharmaaaa** [comment]
You can clone it using:
``` 
git clone https://github.com/pawansharmaaaa/Lip_Wise_GFPGAN.git
```
